#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/dev -mindepth 1 -maxdepth 1 -type d | fzf --reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    # open editor
    tmux send-keys "nvim" C-m
    # add lower split with 20% height
    tmux split-window -v -l 20 -c $selected
    # select editor pane
    tmux select-pane -t 1
fi

tmux switch-client -t $selected_name
